require('config')
require('keybindings')
require('packerPlugins')
require('welcomescreen')
require('nightFox')
-- require('nightflyTheme')
-- require('nordSetting')
-- require('nordSetting2')
-- require('catppuccinTheme')
-- require('colorScheme')
-- require ('lualine').setup({options = { theme = 'nightfly' }})
require('codeFormatter')
-- require('tundraTheme')
require('telescope')
require('lsp_autocomplete')


-- vim.api.nvim_exec([[inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"]],false)
-- vim.api.nvim_exec([[inoremap <silent><expr> <c-space> coc#refresh()]],false) 
