require('config')
require('keybindings')
require('packerPlugins')
require('welcomescreen')
require('nightflyTheme')
require('codeFormatter')
require('telescope')
require('lsp_autocomplete')
require('lualine-setup')
require('tabline')

